apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service
  namespace: restaurant
  labels:
    app: booking-service
    version: "1.0.0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: booking-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: booking-service
        version: "1.0.0"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path:   "/metrics"
        prometheus.io/port:   "3000"
    spec:
      serviceAccountName: booking-service

      # SecurityContext au niveau du Pod - recommandé
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001

      containers:
        - name: booking-service
          image: restaurant-booking:latest         # ← image légère publique
          imagePullPolicy: Never
          
          ports:
            - name: http
              containerPort: 3000      # Corrigé (check correspond au Dockerfile
              protocol: TCP

          # SecurityContext au niveau du container
          securityContext:
            # runAsUser: 0
            allowPrivilegeEscalation: false
            # runAsUser: 1001        # Optionnel : déjà défini au pod level

          env:
            - name: PORT
              value: "3000"
            - name: NODE_ENV
              value: "production"
            - name: DB_PATH
              value: "/app/data/bookings.db"
            - name: ERROR_INJECTION_RATE
              valueFrom:
                configMapKeyRef:
                  name: booking-service-config
                  key: ERROR_INJECTION_RATE
          volumeMounts:
            - name: booking-data
              mountPath: /app/data
             

          resources:
            requests:
              cpu:    "100m"
              memory: "128Mi"
            limits:
              cpu:    "500m"
              memory: "256Mi"

          livenessProbe:
            httpGet:
              path: /health
              port: 3000                   # ← /health n'existe pas sur nginx pur
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10

      volumes:
        - name: booking-data
          persistentVolumeClaim:
            claimName: booking-data-pvc
